### ISSUE TITLE
wp-post-meta-revisions.php needs to be patched

### ISSUE THREAD

**Issue by mourique** [hingst/layotter#25] opened 2017-07-25 15:06 UTC
Layotter Elements currently do not get saved correctly into revisions. There is a bug in the included lib. See https://github.com/adamsilverstein/wp-post-meta-revisions/pull/28 for a working patch.

**Comment by hingst** [comment] 2017-08-06 19:22
Thanks for reporting. I was unable to reproduce any issues with Layotter meta data in revisions though, could you please add details on how to reproduce?

**Comment by hingst** [comment] 2017-08-23 17:25
Hi @mourique and @krafit -- I'd love to fix something here, but I can't fix what I can't reproduce. Please add some more info or I'll have to close this issue

**Comment by mourique** [comment] 2017-08-30 12:23
Hi @hingst sorry for being quiet. I'll try to reproduce and give instructions this week!

**Comment by hingst** [comment] 2017-09-21 21:02
Feel free to reopen with more info

**Closed as completed by hingst** 2017-09-21 21:02 UTC

**Comment by MatzeKitt** [comment] 2018-01-15 14:02
Currently I have an installation where we are partly able to produce this issue. If you want to take a look I could create a login for you.

It would be great for us if you take a look, @hingst . 🙂
